--liquibase formatted sql

--changeset akulov_a:1
CREATE TABLE FILE_FILM_MODEL
(
    ID          NUMBER NOT NULL PRIMARY KEY UNIQUE,
    FILM_YEAR   VARCHAR2(4),
    DESCRIPTION VARCHAR2(2000),
    WIN         NUMBER(1)
);

CREATE SEQUENCE FILE_FILM_SEQ;

CREATE TABLE IMDB_FILM_MODEL
(
    IMDB_ID    VARCHAR2(100) NOT NULL PRIMARY KEY,
    TITLE      VARCHAR(1000),
    FILM_YEAR  VARCHAR(10),
    BOX_OFFICE NUMBER,
    POSTER     VARCHAR(1000),
    GENRE      VARCHAR(1000),
    PLOT       VARCHAR(4000)
);

CREATE TABLE FILM_AWARD_RATING
(
    ID                 NUMBER NOT NULL PRIMARY KEY NOT NULL,
    IMDB_FILM_MODEL_ID VARCHAR2(100),
    WIN                NUMBER(1)
);

ALTER TABLE FILM_AWARD_RATING
    ADD CONSTRAINT FK_FILM_AWARD_RATING_ON_IMDB_FILM_MODEL FOREIGN KEY (IMDB_FILM_MODEL_ID) REFERENCES IMDB_FILM_MODEL (IMDB_ID);

CREATE SEQUENCE FILM_AWARD_RATING_SEQ;

CREATE TABLE FILM_RATING
(
    ID                 NUMBER NOT NULL PRIMARY KEY NOT NULL,
    FILM_ID            NUMBER,
    RATE               NUMBER
);

CREATE SEQUENCE FILM_RATING_SEQ;